### ISSUE TITLE
Is it possible to estimate duration without predefining restrictions

### ISSUE THREAD

**Issue by guochun-yang** [demsarjure/autohrf#1]
The autohrf seems to only work if we give it several predefined duration options, but the possible duration settings are discrete. I am wondering if it is possible to estimate the duration as a continuous variable, similar as the beta coefficient, in the GLM? Thanks!

**Comment by demsarjure** [comment]
Hi, to optimize the speed at which the algorithm traverses the search space we are indeed discretizing the time domain. We picked a precision with 2 decimal points. This choice was based on our domain knowledge and existing practices in the lab. Before autohrf we were testing various manually developed models and the smallest difference between them was on the second decimal, so this is why we picked that precision.

If you think it would be useful, I can easily add precision as a parameter to the library. This way users could pick arbitrary precision for the time domain. Like I said this would be trivial to do, and if you find it beneficial I will gladly add it.
